variables:
  COMPOSER_HOME: $CI_PROJECT_DIR/.composer
  GIT_SUBMODULE_STRATEGY: normal
  MYSQL_DATABASE: ridi_pay
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  PHPUNIT_DATABASE_URL: mysql://root@mariadb/ridi_pay

cache:
  key: composer
  paths:
    - .composer/cache/

before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'

stages:
  - test
  - build
  - deploy
  - notify

.php-test: &php-test
  image: ridibooks/store-php-test:7.2
  services:
    - mariadb:10.3

composer:
  <<: *php-test
  stage: test
  script:
    - composer validate
    - composer install
  except:
    - schedules
    - triggers

phpunit:
  <<: *php-test
  stage: test
  script:
    - composer install
    - vendor/bin/phpunit --colors=never
  except:
    - schedules
    - triggers

phpcs:
  <<: *php-test
  stage: test
  script:
    - composer install
    - vendor/bin/phpcs --standard=docs/lint/php/ruleset.xml
  except:
    - schedules
    - triggers


