language: php
php:
  - '7.2'

sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - docker run -d --name mariadb -e "MYSQL_DATABASE=ridi_pay" -e "MYSQL_ALLOW_EMPTY_PASSWORD=yes" mariadb:10.3
  - docker run -d --name redis redis:latest
  - |
    docker run -itd \
      -v $(pwd):/app \
      --name test \
      --link redis:redis \
      --link mariadb:mariadb \
      ridibooks/store-php-test:7.2 \
      /bin/bash
  - |
    docker run -itd \
      -v $(pwd)/docs/api:/app \
      --name node \
      node:alpine \
      /bin/sh

install:
  - docker exec -it -w /app test /bin/bash -c "composer validate && composer install"
  - docker exec -it node sh -c "apk --update add git py3-pip && pip3 install awscli && yarn global add redoc-cli styled-components"

stages:
  - test
  - docs

jobs:
  include:
    - stage: test
      name: phpunit
      script: docker exec -it -w /app test bash -c "vendor/bin/phpunit --colors=never --coverage-clover=coverage.xml"
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: test
      name: phpcs
      script: docker exec -it -w /app test bash -c "vendor/bin/phpcs --standard=docs/lint/php/ruleset.xml"
    - stage: docs
      name: api
      script: php $(pwd)/docs/api/api_scanner.php > $(pwd)/docs/api/api.json
      after_success:
        - |
          docker exec -it \
            -w /app \
            -e "AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID" \
            -e "AWS_SECRET_ACCESS_KEY=$PROD_AWS_SECRET_ACCESS_KEY" \
            node \
            sh -c "redoc-cli bundle -o api.html api.json && aws s3 cp api.html s3://ridi-pay-backend-api-doc"
