language: php
php:
  - '7.2'

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - wget https://download.libsodium.org/libsodium/releases/LATEST.tar.gz && tar -xf LATEST.tar.gz
  - cd libsodium-stable && ./configure && make && make check && sudo make install && cd ..
  - pecl install libsodium
  - mysql -e 'CREATE DATABASE ridi_pay'

install:
  - composer validate
  - composer install

stages:
  - test

services:
  - docker
  - mariadb
  - redis-server

env:
  - PHPUNIT_DATABASE_URL=mysql://root@127.0.0.1/ridi_pay REDIS_HOST=127.0.0.1

jobs:
  include:
    - stage: test
      name: phpunit
      script: vendor/bin/phpunit --colors=never
    - stage: test
      name: phpcs
      script: vendor/bin/phpcs --standard=docs/lint/php/ruleset.xml
