sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - docker run -d --name mariadb -e "MYSQL_DATABASE=ridi_pay" -e "MYSQL_ALLOW_EMPTY_PASSWORD=yes" mariadb:10.3
  - docker run -d --name redis redis:latest
  - docker run -itd -v $(pwd):/app --name test --link redis:redis --link mariadb:mariadb ridibooks/store-php-test:7.2 /bin/bash

install:
  - docker exec -it -w /app test /bin/bash -c "composer validate && composer install"

stages:
  - test

jobs:
  include:
    - stage: test
      name: phpunit
      script: docker exec -it -w /app test /bin/bash -c "vendor/bin/phpunit --colors=never"
    - stage: test
      name: phpcs
      script: docker exec -it -w /app test /bin/bash -c "vendor/bin/phpcs --standard=docs/lint/php/ruleset.xml"
