version: "3"

services:
  app:
    build: .
    ports:
      - 80
    environment:
      - APP_ENV=${APP_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - KCP_HTTP_PROXY_URL=${KCP_HTTP_PROXY_URL}
      - OAUTH2_CLIENT_ID=${OAUTH2_CLIENT_ID}
      - OAUTH2_CLIENT_SECRET=${OAUTH2_CLIENT_SECRET}
      - PARTNER_SECRET_KEY_SECRET=${PARTNER_SECRET_KEY_SECRET}
      - PG_BILL_KEY_SECRET=${PG_BILL_KEY_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - RIDIBOOKS_SERVER_HOST=${RIDIBOOKS_SERVER_HOST}
      - RIDISELECT_URL=${RIDISELECT_URL}
      - RIDI_PAY_URL=${RIDI_PAY_URL}
      - RIDI_PAY_TO_RIDISELECT_PRIVATE_KEY=${RIDI_PAY_TO_RIDISELECT_PRIVATE_KEY}
      - RIDI_PAY_TO_STORE_PRIVATE_KEY=${RIDI_PAY_TO_STORE_PRIVATE_KEY}
      - RIDISELECT_TO_RIDI_PAY_PUBLIC_KEY=${RIDISELECT_TO_RIDI_PAY_PUBLIC_KEY}
      - STORE_TO_RIDI_PAY_PUBLIC_KEY=${STORE_TO_RIDI_PAY_PUBLIC_KEY}
    depends_on:
      - kcp
      - mariadb
      - redis
    command: [
      'bash',
      '-c',
      'chmod +x /app/bin/wait-for-it.sh && /app/bin/wait-for-it.sh mariadb:3306 && /app/bin/wait-for-it.sh kcp:80 -- yarn run test'
    ]
  kcp:
    image: 023315198496.dkr.ecr.ap-northeast-2.amazonaws.com/ridi/kcp-http-proxy:latest
    ports:
      - 80
    environment:
      - APP_ENV=${APP_ENV}
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    depends_on:
      - dynamodb
    command: ['bash', '-c', 'yarn run init-db && yarn start']
  mariadb:
    image: mariadb:10.3
    ports:
      - 3306
    environment:
      - MYSQL_DATABASE=ridi_pay
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: redis:latest
  dynamodb:
    image: amazon/dynamodb-local
