version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/certs:/etc/nginx/certs:ro
      - ./config/docker/nginx-proxy/vhost.d:/etc/nginx/vhost.d
    ports:
      - 80:80
      - 443:443
  api:
    container_name: api
    build: .
    ports:
      - 80
    environment:
      - VIRTUAL_HOST=api.pay.ridi.io
      - APP_ENV=dev
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    volumes:
      - .:/app
  mariadb:
    image: mariadb:10.3
    container_name: mariadb
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=ridi_pay
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./data/redis:/data
