version: "3"

services:
  apache:
    image: ridi/pay:latest
    container_name: apache
    build:
      context: .
      args:
        SITE: api.pay.local.ridi.io
    ports:
      - 80:80
      - 443:443
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    volumes:
      - .:/app
  mariadb:
    image: mariadb:10.3
    container_name: mariadb
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=ridi_pay
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./data/redis:/data
