version: "3"

services:
  api:
    build: .
    ports:
      - 80
    environment:
      - APP_ENV=dev
    volumes:
      - .:/app
    entrypoint: apachectl -D FOREGROUND
    logging:
      driver: fluentd
      options:
        tag: dev.ridi-pay.backend.api
    depends_on:
      - fluentd
  fluentd:
    build: ./config/docker/fluentd
    ports:
      - 24224:24224
    volumes:
      - ./config/docker/fluentd:/fluentd/etc
    environment:
      - FLUENTD_CONF=fluent.local.conf
  mariadb:
    image: mariadb:10.3
    ports:
      - 3306:3306
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=ridi_pay
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  mariadb_test:
    image: mariadb:10.3
    volumes:
      - ./data/mariadb_test:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=ridi_pay
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: redis:latest
    volumes:
      - ./data/redis:/data
