version: "3"

services:
  api:
    build: .
    ports:
      - 80
    environment:
      - APP_ENV=dev
    volumes:
      - .:/app
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${EXTERNAL_NETWORK:-ridi}"
      - "traefik.frontend.rule=Host:api.pay.local.ridi.io"
    networks:
      traefik:
        aliases:
          - pay-api
      default:
  kcp:
    image: 023315198496.dkr.ecr.ap-northeast-2.amazonaws.com/ridi/kcp-http-proxy:latest
    ports:
      - 80
    environment:
      - APP_ENV=dev
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    depends_on:
      - dynamodb
  mariadb:
    image: mariadb:10.3
    ports:
      - 3306
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=ridi_pay
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  mariadb_test:
    image: mariadb:10.3
    volumes:
      - ./data/mariadb_test:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=ridi_pay
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: redis:latest
    volumes:
      - ./data/redis:/data
  dynamodb:
    image: amazon/dynamodb-local
    command: ['-jar', 'DynamoDBLocal.jar', '-sharedDb', '-dbPath', '/home/dynamodblocal/data/']
    volumes:
      - ./data/dynamodb:/home/dynamodblocal/data
networks:
  traefik:
    external:
      name: ${EXTERNAL_NETWORK:-ridi}
