version: "3"

services:
  api:
    build: .
    ports:
      - 80
    environment:
      - VIRTUAL_HOST=api.pay.local.ridi.io
      - APP_ENV=dev
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    volumes:
      - .:/app
    logging:
      driver: fluentd
      options:
        tag: dev.ridi-pay.backend.api
    depends_on:
      - fluentd
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:api.pay.local.ridi.io"
    networks:
      - traefik
  fluentd:
    build: ./config/docker/fluentd
    ports:
      - 24224:24224
    volumes:
      - ./config/docker/fluentd:/fluentd/etc
    environment:
      - FLUENTD_CONF=fluent.local.conf
  mariadb:
    image: mariadb:10.3
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=ridi_pay
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:mariadb.docker.localhost"
    networks:
      - traefik
  redis:
    image: redis:latest
    volumes:
      - ./data/redis:/data
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:redis.docker.localhost"
    networks:
      - traefik
networks:
  traefik:
    external:
      name: traefik
