version: "3"

services:
  app:
    image: 023315198496.dkr.ecr.ap-northeast-2.amazonaws.com/ridi/pay-backend:${GIT_REVISION}
    build: .
    ports:
      - 80:80
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-2
        awslogs-group: ${APP_ENV}.ridi-pay-backend
        awslogs-stream-prefix: ${APP_ENV}.ridi-pay-backend
