version: "3"

services:
  api:
    image: 023315198496.dkr.ecr.ap-northeast-2.amazonaws.com/ridi/pay-backend:${GIT_REVISION}
    container_name: api
    build: .
    ports:
      - 80
    environment:
      - APP_ENV=${APP_ENV}
      - GIT_REVISION=${GIT_REVISION}
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-2
        awslogs-group: ${APP_ENV}.ridi-pay-backend
        awslogs-stream-prefix: ${APP_ENV}.ridi-pay-backend
