version: "3"

services:
  apache:
    image: ridibooks/pay:${TAG}
    container_name: apache
    build:
      context: .
      args:
        SITE: pay.ridibooks.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/app
