version: "3"

services:
  api:
    image: 023315198496.dkr.ecr.ap-northeast-2.amazonaws.com/ridi/pay-backend:${GIT_REVISION}
    container_name: api
    build: ../..
    ports:
      - 80
    environment:
      - APP_ENV=${APP_ENV}
      - GIT_REVISION=${GIT_REVISION}
    logging:
      driver: fluentd
      options:
        fluentd-address: ${FLUENTD_ADDRESS}
        tag: ${APP_ENV}.ridi-pay.backend.api
