version: 1

task_definition:
  services:
    api:
      mem_limit: 256m
      mem_reservation: 128m

run_params:
  task_placement:
    constraints:
      - type: memberOf
        expression: "attribute:service != fluentd"
