version: 1

task_definition:
  task_role_arn: apiRole
  task_execution_role: ecsTaskExecutionRole
  services:
    api:
      mem_limit: 256m
      mem_reservation: 128m

run_params:
  task_placement:
    constraints:
      - type: memberOf
        expression: "attribute:service !exists"
